services:
  db:
    build: ./db
    restart: always
    container_name: mysql_db
    ports:
      - "4306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: mydatabase
    volumes:
      - ./db/init_db.sh:/docker-entrypoint-initdb.d/init_db.sh
      - db_data:/var/lib/mysql

  backend:
    build: ./backend
    container_name: backend
    ports:
      - "4000:4000"
    volumes:
      - ./backend:/app
    environment:
      - FLASK_ENV=development
    depends_on:
      - db

  frontend:
    build: ./frontend
    container_name: frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
    environment:
      - NODE_ENV=development
    develop:
      watch:
        - action: sync
          path: ./frontend
          target: /app
          ignore:
            - node_modules/
        - action: rebuild
          path: package.json

volumes:
  db_data: