"""Grade pending picks against final scores.

Settlement rules:
  ml     — selection wins straight up.
  rl     — favorite -1.5 covers iff it wins by >= 2; underdog +1.5 covers iff
           it wins outright or loses by exactly 1.
  total  — over/under vs total runs; exact = push. (Totals picks are not
           generated by the MVP rules yet, but grading supports them so the
           ledger stays future-proof.)
  void   — postponed/suspended games (no Final after their date) refund the
           stake.

Profit at flat stake: win -> stake * (decimal - 1); loss -> -stake;
push/void -> 0.
"""

from __future__ import annotations

import pandas as pd

from . import store
from .timeutil import now_utc, utc_iso


def _result_for_pick(pick, game) -> tuple[str, str] | None:
    """Return (status, final_score) or None when the game has no final yet."""
    status = str(game["status"])
    home_score = game["home_score"]
    away_score = game["away_score"]

    if status != "Final" or pd.isna(home_score) or pd.isna(away_score):
        if status in ("Postponed", "Suspended", "Cancelled"):
            return "void", ""
        return None

    home_score, away_score = int(home_score), int(away_score)
    final_score = f"{game['away_team']} {away_score} - {game['home_team']} {home_score}"
    selection = pick["selection"]
    sel_is_home = selection == game["home_team"]
    sel_score = home_score if sel_is_home else away_score
    opp_score = away_score if sel_is_home else home_score
    margin = sel_score - opp_score

    market = pick["market"]
    if market == "ml":
        if margin == 0:  # cannot happen in MLB, defensive
            return "push", final_score
        return ("win" if margin > 0 else "loss"), final_score
    if market == "rl":
        line = float(pick["line"])
        adjusted = margin + line
        if adjusted == 0:
            return "push", final_score
        return ("win" if adjusted > 0 else "loss"), final_score
    if market == "total":
        total = home_score + away_score
        line = float(pick["line"])
        if total == line:
            return "push", final_score
        is_over = str(selection).lower().startswith("over")
        won = total > line if is_over else total < line
        return ("win" if won else "loss"), final_score
    return None


def grade_pending() -> pd.DataFrame:
    """Settle every pending pick whose game has a final (or void) result.

    Returns the settlements dataframe (possibly empty)."""
    picks = store.load_picks()
    games = store.load_games()
    if picks.empty or games.empty:
        return pd.DataFrame()

    pending = picks[picks["status"] == "pending"]
    games_by_pk = games.set_index("game_pk")
    settlements = []
    for _, pick in pending.iterrows():
        pk = pick["game_pk"]
        if pk not in games_by_pk.index:
            continue
        game = games_by_pk.loc[pk]
        outcome = _result_for_pick(pick, game)
        if outcome is None:
            continue
        status, final_score = outcome
        stake = float(pick["stake"])
        if status == "win":
            profit = round(stake * (float(pick["price_decimal"]) - 1), 2)
        elif status == "loss":
            profit = -stake
        else:  # push / void
            profit = 0.0
        settlements.append(
            {
                "pick_id": pick["pick_id"],
                "status": status,
                "settled_ts_utc": utc_iso(now_utc()),
                "final_score": final_score,
                "profit": profit,
            }
        )

    df = pd.DataFrame(settlements)
    if not df.empty:
        store.settle_picks(df)
    return df
