name: Generate Badges

on:
  schedule:
    - cron: '0 0 * * *'  # Runs every day
  workflow_dispatch:  # Allows manual triggering of the workflow

jobs:
  badges:
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Set the GH_TOKEN for the entire job

    steps:
      - name: Check out the repository
        uses: actions/checkout@v4  # Updated to v4

      - name: Set up Node.js
        uses: actions/setup-node@v4  # Updated to v4

      - name: Create Badges Directory
        run: mkdir -p badges  # Ensure the badges directory exists

      - name: Remove Old Badges
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git rm --cached badges/*.svg
          git commit -m "Removing old badges"
          git push

      - name: Install Dependencies
        run: npm install -g badge-maker

      - name: Generate Badge for Open Issues
        run: |
          OPEN_ISSUES=$(gh api -H "Accept: application/vnd.github+json" repos/gitchrisqueen/panthera/issues --jq 'map(select(.state=="open")) | length' || echo "0")
          TIMESTAMP=$(date +"%m/%d/%y")
          npx badge "$OPEN_ISSUES" "Open Issues" "blue" "grey" @flat > badges/open_issues.svg

      - name: Generate Badge for Closed Issues
        run: |
          CLOSED_ISSUES=$(gh api -H "Accept: application/vnd.github+json" repos/gitchrisqueen/panthera/issues?state=closed --jq 'length' || echo "0")
          TIMESTAMP=$(date +"%m/%d/%y")
          npx badge "$CLOSED_ISSUES" "Closed Issues" "brightgreen" "grey" @flat > badges/closed_issues.svg

      - name: Commit New Badges
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add -f badges/*.svg
          git commit -m "Update badges" -a || echo "No changes to commit"
          git push

      - name: Purge Cache
        shell: bash
        run: |
          # TODO: Fix the badge generation step that purges the github cache
          #!/bin/bash
          
          # Fetch SVG files from the badges folder
          svg_files=$(find badges -name "*.svg")
          
          # Process each SVG file
          for svg_file in $svg_files; do
            # Get the raw content URL for the SVG file
            raw_url="https://github.com/${{ github.repository }}/raw/main/$svg_file"
          
            # Construct the camo URL
            camo_url=$(curl -sI -H "Authorization: token $GH_TOKEN" "$raw_url" | grep -i "location" | cut -d' ' -f2 | tr -d '\r')
          
            if [ -n "$camo_url" ]; then
              echo "Purging cache for $svg_file"
              curl -X PURGE -H "Authorization: token $GH_TOKEN" "$camo_url"
            else
              echo "No camo URL found for $svg_file"
            fi
          done