name: Generate Badges

on:
  schedule:
    - cron: '0 * * * *'  # Runs every hour
  workflow_dispatch:  # Allows manual triggering of the workflow

jobs:
  badges:
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Set the GH_TOKEN for the entire job

    steps:
      - name: Check out the repository
        uses: actions/checkout@v4  # Updated to v4

      - name: Set up Node.js
        uses: actions/setup-node@v4  # Updated to v4

      - name: Create Badges Directory
        run: mkdir -p badges  # Ensure the badges directory exists

      - name: Remove Old Badges
        run: rm -f badges/*.svg  # Remove old badge files

      - name: Install Dependencies
        run: npm install -g badge-maker

      - name: Generate Badge for Open Issues
        run: |
          OPEN_ISSUES=$(gh api -H "Accept: application/vnd.github+json" repos/gitchrisqueen/panthera/issues --jq 'map(select(.state=="open")) | length' || echo "0")
          TIMESTAMP=$(date +"%m/%d/%y")
          npx badge "$OPEN_ISSUES" "Open Issues | Updated: $TIMESTAMP" "blue" "grey" @flat > badges/open_issues.svg

      - name: Generate Badge for Closed Issues
        run: |
          CLOSED_ISSUES=$(gh api -H "Accept: application/vnd.github+json" repos/gitchrisqueen/panthera/issues?state=closed --jq 'length' || echo "0")
          TIMESTAMP=$(date +"%m/%d/%y")
          npx badge "$CLOSED_ISSUES" "Closed Issues | Updated: $TIMESTAMP" "brightgreen" "grey" @flat > badges/closed_issues.svg

      - name: Purge Cache
        uses: kevincobain2000/action-camo-purge@v1

      - name: Commit Badges
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add -f badges/open_issues.svg badges/closed_issues.svg
          git commit -m "Update badges"
          git push